import type { Hit, Media, Note, Partner, Skill, TrainingLog } from './types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString();

export const seedSkills: Skill[] = [
  {
    id: 'skill-k-guard',
    name: 'K Guard Entry',
    stage: 'mechanics',
    active: true,
    lastTouchedAt: daysAgo(2),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(2),
  },
  {
    id: 'skill-rnc',
    name: 'RNC Finish',
    stage: 'resistance',
    active: true,
    lastTouchedAt: daysAgo(1),
    createdAt: daysAgo(41),
    updatedAt: daysAgo(1),
  },
  {
    id: 'skill-knee-lever',
    name: 'Half Guard Knee Lever',
    stage: 'mechanics',
    active: true,
    lastTouchedAt: daysAgo(6),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(6),
  },
  {
    id: 'skill-arm-triangle',
    name: 'Arm Triangle',
    stage: 'proven',
    active: true,
    lastTouchedAt: daysAgo(8),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(8),
  },
  {
    id: 'skill-wrist-ride',
    name: 'Wrist Ride Back Take',
    stage: 'mechanics',
    active: true,
    lastTouchedAt: daysAgo(5),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(5),
  },
  {
    id: 'skill-single-leg-x',
    name: 'Single Leg X Sweep',
    stage: 'resistance',
    active: true,
    lastTouchedAt: daysAgo(7),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(7),
  },
];

export const seedPartners: Partner[] = [
  { id: 'partner-alex', name: 'Alex', createdAt: daysAgo(36), updatedAt: daysAgo(1) },
  { id: 'partner-dillon', name: 'Dillon', createdAt: daysAgo(28), updatedAt: daysAgo(3) },
  { id: 'partner-jordan', name: 'Jordan', createdAt: daysAgo(24), updatedAt: daysAgo(2) },
  { id: 'partner-sam', name: 'Sam', createdAt: daysAgo(12), updatedAt: daysAgo(4) },
];

export const seedTrainingLogs: TrainingLog[] = [
  {
    id: 'log-k-guard-1',
    skillId: 'skill-k-guard',
    type: 'constraint_game',
    occurredAt: daysAgo(2),
    durationMinutes: 12,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'log-rnc-1',
    skillId: 'skill-rnc',
    type: 'rolling',
    occurredAt: daysAgo(1),
    durationMinutes: 30,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'log-rnc-study-1',
    skillId: 'skill-rnc',
    type: 'study',
    occurredAt: daysAgo(6),
    durationMinutes: 18,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: 'log-rnc-drilling-1',
    skillId: 'skill-rnc',
    type: 'dialogue_drilling',
    occurredAt: daysAgo(4),
    durationMinutes: 22,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: 'log-rnc-game-1',
    skillId: 'skill-rnc',
    type: 'constraint_game',
    occurredAt: daysAgo(3),
    durationMinutes: 15,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'log-rnc-alex-drilling',
    skillId: 'skill-rnc',
    type: 'dialogue_drilling',
    occurredAt: daysAgo(9),
    durationMinutes: 16,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 'log-rnc-open-mat',
    skillId: 'skill-rnc',
    type: 'rolling',
    occurredAt: daysAgo(14),
    durationMinutes: 35,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'log-rnc-positional',
    skillId: 'skill-rnc',
    type: 'constraint_game',
    occurredAt: daysAgo(21),
    durationMinutes: 20,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: 'log-rnc-back-control',
    skillId: 'skill-rnc',
    type: 'constraint_game',
    occurredAt: daysAgo(29),
    durationMinutes: 18,
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: 'log-k-guard-alex-counter',
    skillId: 'skill-k-guard',
    type: 'constraint_game',
    occurredAt: daysAgo(12),
    durationMinutes: 10,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 'log-k-guard-dillon-counter',
    skillId: 'skill-k-guard',
    type: 'constraint_game',
    occurredAt: daysAgo(3),
    durationMinutes: 16,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'log-k-guard-open-mat',
    skillId: 'skill-k-guard',
    type: 'rolling',
    occurredAt: daysAgo(10),
    durationMinutes: 28,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'log-wrist-ride-alex-rounds',
    skillId: 'skill-wrist-ride',
    type: 'rolling',
    occurredAt: daysAgo(16),
    durationMinutes: 24,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  {
    id: 'log-wrist-ride-positional',
    skillId: 'skill-wrist-ride',
    type: 'constraint_game',
    occurredAt: daysAgo(2),
    durationMinutes: 18,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'log-wrist-ride-chain',
    skillId: 'skill-wrist-ride',
    type: 'dialogue_drilling',
    occurredAt: daysAgo(11),
    durationMinutes: 22,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: 'log-wrist-ride-open-mat',
    skillId: 'skill-wrist-ride',
    type: 'rolling',
    occurredAt: daysAgo(23),
    durationMinutes: 30,
    createdAt: daysAgo(23),
    updatedAt: daysAgo(23),
  },
  {
    id: 'log-wrist-ride-ride-time',
    skillId: 'skill-wrist-ride',
    type: 'constraint_game',
    occurredAt: daysAgo(30),
    durationMinutes: 20,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'log-arm-triangle-1',
    skillId: 'skill-arm-triangle',
    type: 'rolling',
    occurredAt: daysAgo(8),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: 'log-knee-lever-1',
    skillId: 'skill-knee-lever',
    type: 'dialogue_drilling',
    occurredAt: daysAgo(6),
    durationMinutes: 18,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: 'log-knee-lever-rounds',
    skillId: 'skill-knee-lever',
    type: 'constraint_game',
    occurredAt: daysAgo(11),
    durationMinutes: 15,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: 'log-knee-lever-open-mat',
    skillId: 'skill-knee-lever',
    type: 'rolling',
    occurredAt: daysAgo(15),
    durationMinutes: 25,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    id: 'log-knee-lever-study-rounds',
    skillId: 'skill-knee-lever',
    type: 'rolling',
    occurredAt: daysAgo(25),
    durationMinutes: 24,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: 'log-single-leg-x-1',
    skillId: 'skill-single-leg-x',
    type: 'constraint_game',
    occurredAt: daysAgo(7),
    durationMinutes: 20,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'log-single-leg-x-positional',
    skillId: 'skill-single-leg-x',
    type: 'constraint_game',
    occurredAt: daysAgo(4),
    durationMinutes: 16,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: 'log-single-leg-x-rounds',
    skillId: 'skill-single-leg-x',
    type: 'rolling',
    occurredAt: daysAgo(13),
    durationMinutes: 24,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    id: 'log-single-leg-x-open-mat',
    skillId: 'skill-single-leg-x',
    type: 'rolling',
    occurredAt: daysAgo(19),
    durationMinutes: 30,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    id: 'log-single-leg-x-chain-drill',
    skillId: 'skill-single-leg-x',
    type: 'dialogue_drilling',
    occurredAt: daysAgo(31),
    durationMinutes: 22,
    createdAt: daysAgo(31),
    updatedAt: daysAgo(31),
  },
  {
    id: 'log-arm-triangle-positional',
    skillId: 'skill-arm-triangle',
    type: 'constraint_game',
    occurredAt: daysAgo(10),
    durationMinutes: 14,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'log-arm-triangle-open-mat',
    skillId: 'skill-arm-triangle',
    type: 'rolling',
    occurredAt: daysAgo(18),
    durationMinutes: 22,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
];

export const seedNotes: Note[] = [
  {
    id: 'note-k-guard-1',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-1',
    body: 'Entry worked when I kept my knee line hidden and framed before turning in.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'note-rnc-1',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-1',
    body: 'Hand fight improved when I got chest-to-back tighter before attacking the neck.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'note-wrist-ride-1',
    skillId: 'skill-wrist-ride',
    body: 'Ask coach about the hip switch when they post the free hand.',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'note-rnc-alex-drilling',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-alex-drilling',
    body: 'Alex stripped the choking hand unless I hid it behind the shoulder first.',
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 'note-k-guard-alex-counter',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-alex-counter',
    body: 'Alex beat the entry when my outside leg floated instead of clamping the hip.',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 'note-knee-lever-1',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-1',
    body: 'Lever was strongest when I got my knee under the thigh before pulling the far hip.',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: 'note-single-leg-x-1',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-1',
    body: 'Sam based wide; switching to the outside heel tilt opened the sweep.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
];

export const seedHits: Hit[] = [
  {
    id: 'hit-k-guard-alex',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-1',
    partnerId: 'partner-alex',
    count: 2,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'hit-k-guard-jordan',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-1',
    partnerId: 'partner-jordan',
    count: 1,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'hit-rnc-alex',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-1',
    partnerId: 'partner-alex',
    count: 3,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'hit-rnc-open',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-1',
    count: 2,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'hit-rnc-game-jordan',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-game-1',
    partnerId: 'partner-jordan',
    count: 2,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'hit-rnc-alex-drilling',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-alex-drilling',
    partnerId: 'partner-alex',
    count: 2,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 'hit-rnc-open-mat-alex',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-open-mat',
    partnerId: 'partner-alex',
    count: 7,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'hit-rnc-positional-sam',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-positional',
    partnerId: 'partner-sam',
    count: 6,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: 'hit-rnc-positional-open',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-positional',
    count: 9,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: 'hit-rnc-back-control-alex',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-back-control',
    partnerId: 'partner-alex',
    count: 5,
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: 'hit-rnc-back-control-open',
    skillId: 'skill-rnc',
    trainingLogId: 'log-rnc-back-control',
    count: 5,
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: 'hit-k-guard-alex-counter',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-alex-counter',
    partnerId: 'partner-alex',
    count: 1,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 'hit-k-guard-dillon-counter',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-dillon-counter',
    partnerId: 'partner-dillon',
    count: 4,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'hit-k-guard-open-mat-alex',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-open-mat',
    partnerId: 'partner-alex',
    count: 5,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'hit-k-guard-open-mat-open',
    skillId: 'skill-k-guard',
    trainingLogId: 'log-k-guard-open-mat',
    count: 4,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'hit-wrist-ride-alex-rounds',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-alex-rounds',
    partnerId: 'partner-alex',
    count: 1,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  {
    id: 'hit-wrist-ride-positional-jordan',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-positional',
    partnerId: 'partner-jordan',
    count: 7,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'hit-wrist-ride-chain-alex',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-chain',
    partnerId: 'partner-alex',
    count: 6,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: 'hit-wrist-ride-open-mat-sam',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-open-mat',
    partnerId: 'partner-sam',
    count: 5,
    createdAt: daysAgo(23),
    updatedAt: daysAgo(23),
  },
  {
    id: 'hit-wrist-ride-ride-time-jordan',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-ride-time',
    partnerId: 'partner-jordan',
    count: 6,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'hit-wrist-ride-ride-time-open',
    skillId: 'skill-wrist-ride',
    trainingLogId: 'log-wrist-ride-ride-time',
    count: 4,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'hit-wrist-ride-alex',
    skillId: 'skill-wrist-ride',
    partnerId: 'partner-alex',
    count: 3,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'hit-wrist-ride-sam',
    skillId: 'skill-wrist-ride',
    partnerId: 'partner-sam',
    count: 2,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'hit-arm-triangle-sam',
    skillId: 'skill-arm-triangle',
    trainingLogId: 'log-arm-triangle-1',
    partnerId: 'partner-sam',
    count: 1,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: 'hit-knee-lever-jordan',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-1',
    partnerId: 'partner-jordan',
    count: 4,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: 'hit-knee-lever-rounds-alex',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-rounds',
    partnerId: 'partner-alex',
    count: 6,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    id: 'hit-knee-lever-open-mat-open',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-open-mat',
    count: 5,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    id: 'hit-knee-lever-study-rounds-sam',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-study-rounds',
    partnerId: 'partner-sam',
    count: 5,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: 'hit-knee-lever-study-rounds-open',
    skillId: 'skill-knee-lever',
    trainingLogId: 'log-knee-lever-study-rounds',
    count: 5,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: 'hit-single-leg-x-sam',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-1',
    partnerId: 'partner-sam',
    count: 6,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'hit-single-leg-x-positional-jordan',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-positional',
    partnerId: 'partner-jordan',
    count: 8,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: 'hit-single-leg-x-rounds-alex',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-rounds',
    partnerId: 'partner-alex',
    count: 5,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    id: 'hit-single-leg-x-rounds-open',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-rounds',
    count: 3,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    id: 'hit-single-leg-x-open-mat-sam',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-open-mat',
    partnerId: 'partner-sam',
    count: 8,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    id: 'hit-single-leg-x-open-mat-open',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-open-mat',
    count: 7,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    id: 'hit-single-leg-x-chain-drill-alex',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-chain-drill',
    partnerId: 'partner-alex',
    count: 8,
    createdAt: daysAgo(31),
    updatedAt: daysAgo(31),
  },
  {
    id: 'hit-single-leg-x-chain-drill-open',
    skillId: 'skill-single-leg-x',
    trainingLogId: 'log-single-leg-x-chain-drill',
    count: 7,
    createdAt: daysAgo(31),
    updatedAt: daysAgo(31),
  },
  {
    id: 'hit-arm-triangle-positional-sam',
    skillId: 'skill-arm-triangle',
    trainingLogId: 'log-arm-triangle-positional',
    partnerId: 'partner-sam',
    count: 3,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'hit-arm-triangle-open-mat-jordan',
    skillId: 'skill-arm-triangle',
    trainingLogId: 'log-arm-triangle-open-mat',
    partnerId: 'partner-jordan',
    count: 4,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
];

export const seedMedia: Media[] = [
  {
    id: 'media-k-guard-1',
    skillId: 'skill-k-guard',
    type: 'youtube',
    url: 'https://www.youtube.com/watch?v=2b7bqY7iZBs&t=233s',
    title: 'How To Do The Perfect BJJ K Guard by Lachlan Giles',
    thumbnailUrl: 'https://i.ytimg.com/vi/2b7bqY7iZBs/hqdefault.jpg',
    notes: 'Reference for entry angle and knee line.',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
];
